Repository hyperwallet/hyperwallet-android-sdk, pull requests merged in 2020-11, with the labels that each got.

#107 DTSERWFOUR-85-update-target-API-level-to-29-for-Core-SDK
  core/build.gradle
  core/src/test/resources/robolectric.properties
Labels: Ready To Test

#108 DTSERWFOUR-162 - Set headers for various sdk params
  core/src/main/java/com/hyperwallet/android/HttpTransaction.java
  core/src/main/java/com/hyperwallet/android/Hyperwallet.java
  core/src/main/java/com/hyperwallet/android/RestTransaction.java
  core/src/test/java/com/hyperwallet/android/RestTransactionBuilderTest.java
  core/src/test/java/com/hyperwallet/android/RestTransactionTest.java
Labels: Ready To Merge

#109 DTSERWFOUR-167 - Add translation files for 33 Languages.
  core/src/main/res/values-bg/strings.xml
  core/src/main/res/values-cs/strings.xml
  core/src/main/res/values-de/strings.xml
  core/src/main/res/values-el/strings.xml
  core/src/main/res/values-es/strings.xml
  core/src/main/res/values-fi/strings.xml
  core/src/main/res/values-fr/strings.xml
  core/src/main/res/values-hr/strings.xml
  core/src/main/res/values-hu/strings.xml
  core/src/main/res/values-in/strings.xml
  core/src/main/res/values-is/strings.xml
  core/src/main/res/values-it/strings.xml
  core/src/main/res/values-ja/strings.xml
  core/src/main/res/values-ko/strings.xml
  core/src/main/res/values-lv/strings.xml
  core/src/main/res/values-mk/strings.xml
  core/src/main/res/values-mn/strings.xml
  core/src/main/res/values-ms/strings.xml
  core/src/main/res/values-nl/strings.xml
  core/src/main/res/values-pl/strings.xml
  core/src/main/res/values-pt-rPT/strings.xml
  core/src/main/res/values-pt/strings.xml
  core/src/main/res/values-ro/strings.xml
  core/src/main/res/values-ru/strings.xml
  core/src/main/res/values-sk/strings.xml
  core/src/main/res/values-sl/strings.xml
  core/src/main/res/values-sv/strings.xml
  core/src/main/res/values-th/strings.xml
  core/src/main/res/values-tr/strings.xml
  core/src/main/res/values-uk/strings.xml
  core/src/main/res/values-vi/strings.xml
  core/src/main/res/values-zh-rCN/strings.xml
  core/src/main/res/values-zh-rTW/strings.xml
  core/src/main/res/values-zh/strings.xml
  core/src/main/res/values/strings.xml
Labels: Ready To Merge, Ready To Test
